name: fluent_translator_generator
description: A code generator for fluent_translator package.
version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: "0.39.14"
  build: ^1.3.0
  build_config: ^0.4.0
  source_gen: ^0.9.0
  csv: ^4.1.0
  fluent_translator: ^0.0.1

dev_dependencies:
  test: ^1.6.0